"""create wrong_words table

Revision ID: 015130d687a7
Revises: f808051ce9db
Create Date: 2025-09-01 00:28:12.842206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015130d687a7'
down_revision = 'f808051ce9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wrong_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_wrong_words')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wrong_words')
    # ### end Alembic commands ###
